### ISSUE TITLE
Support anti-XSRF state parameter 

### ISSUE THREAD

**Issue by thefosk** [Mashape/guardian#11]
https://tools.ietf.org/html/rfc6749#section-10.12

To reproduce the problem that some clients face, follow the following steps:

* Install NoRedirect extension (https://addons.mozilla.org/en-US/firefox/addon/noredirect/) and add a new entry https://guardian.mashape.com/callback
* Go to https://www.mashape.com/ and click "Login with Github"
* Accept the consent screen
* The browser is redirected to `https://guardian.mashape.com/callback?code=9c550ec6cd5f7a7424a7` but the NoRedirect plugin will stop going forward (so the code is not used)
* Just save the url above
* Send the uri to the victim 
* As result the victim is now using the attacker controlled account

The suggestion is to enable the state parameter usage.

**Comment by Nijikokun** [comment]
False, just tested this, there is a session system that requires the same user that started the flow to finish it. It is not a vulnerability and this is not required.

Users attempting this will obtain the following:

```json
{
  "code": "MISSING_SESSION_DETAILS",
  "message": "Session details are missing, perhaps the redirect url is on another server or the request timed out."
}
```
